name: CREATE TABLE - shopify_cltv
run-name: ${{ github.actor }} - CREATE TABLE - shopify_cltv
on: 
  push:
    paths:
      - '**/create_table/cltv_summary/**'
      - '**/.github/workflows/**'

jobs:
  create_shopify_cltv:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository has been cloned to the runner. The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: List files in the repository
        run: |
          ls create_table
      - name: Print wd
          run: |
          pwds
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r create_table/requirements.txt
    
      - name: CREATE TABLE - shopify_cltv
        env: 
          AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }} 
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
        run: python create_table/shopify_cltv/create_table.py 

      - run: echo "Job status - ${{ job.status }}."
